version: '3'
services:

  # Base Images

  php71-fpm-stretch-base:
    image: my127/spryker:7.1-fpm-stretch${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.1
        BASEOS: stretch

  php72-fpm-stretch-base:
    image: my127/spryker:7.2-fpm-stretch${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.2
        BASEOS: stretch

  php73-fpm-stretch-base:
    image: my127/spryker:7.3-fpm-stretch${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: stretch

  php73-fpm-buster-base:
    image: my127/spryker:7.3-fpm-buster${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: buster

  php74-fpm-buster-base:
    image: my127/spryker:7.4-fpm-buster${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: buster

  php74-fpm-bullseye-base:
    image: my127/spryker:7.4-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: bullseye

  php80-fpm-buster-base:
    image: my127/spryker:8.0-fpm-buster${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.0
        BASEOS: buster

  php80-fpm-bullseye-base:
    image: my127/spryker:8.0-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.0
        BASEOS: bullseye

  php81-fpm-bullseye-base:
    image: my127/spryker:8.1-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.1
        BASEOS: bullseye

  php82-fpm-bullseye-base:
    image: my127/spryker:8.2-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.2
        BASEOS: bullseye

  php83-fpm-bookworm-base:
    image: my127/spryker:8.3-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 8.3
        BASEOS: bookworm

  # Console Images

  php71-fpm-stretch-console:
    image: my127/spryker:7.1-fpm-stretch-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.1
        BASEOS: stretch

  php72-fpm-stretch-console:
    image: my127/spryker:7.2-fpm-stretch-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.2
        BASEOS: stretch

  php73-fpm-stretch-console:
    image: my127/spryker:7.3-fpm-stretch-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: stretch

  php73-fpm-buster-console:
    image: my127/spryker:7.3-fpm-buster-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: buster

  php74-fpm-buster-console:
    image: my127/spryker:7.4-fpm-buster-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: buster

  php74-fpm-bullseye-console:
    image: my127/spryker:7.4-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: bullseye

  php80-fpm-buster-console:
    image: my127/spryker:8.0-fpm-buster-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.0
        BASEOS: buster
    depends_on:
      - php80-fpm-buster-base

  php80-fpm-bullseye-console:
    image: my127/spryker:8.0-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.0
        BASEOS: bullseye
    depends_on:
      - php80-fpm-bullseye-base

  php81-fpm-bullseye-console:
    image: my127/spryker:8.1-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.1
        BASEOS: bullseye
    depends_on:
      - php81-fpm-bullseye-base

  php82-fpm-bullseye-console:
    image: my127/spryker:8.2-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.2
        BASEOS: bullseye
    depends_on:
      - php82-fpm-bullseye-base

  php83-fpm-bookworm-console:
    image: my127/spryker:8.3-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 8.3
        BASEOS: bookworm
    depends_on:
      - php83-fpm-bookworm-base
