version: '3'
services:

  # Base Images

  php71-fpm-stretch-base:
    image: my127/spryker:7.1-fpm-stretch
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.1
        BASEOS: stretch

  php72-fpm-stretch-base:
    image: my127/spryker:7.2-fpm-stretch
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.2
        BASEOS: stretch

  php73-fpm-stretch-base:
    image: my127/spryker:7.3-fpm-stretch
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: stretch

  php73-fpm-buster-base:
    image: my127/spryker:7.3-fpm-buster
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: buster

  php74-fpm-buster-base:
    image: my127/spryker:7.4-fpm-buster
    build:
      context: ./
      dockerfile: base.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: buster

  # Console Images

  php71-fpm-stretch-console:
    image: my127/spryker:7.1-fpm-stretch-console
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.1
        BASEOS: stretch

  php72-fpm-stretch-console:
    image: my127/spryker:7.2-fpm-stretch-console
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.2
        BASEOS: stretch

  php73-fpm-stretch-console:
    image: my127/spryker:7.3-fpm-stretch-console
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: stretch

  php73-fpm-buster-console:
    image: my127/spryker:7.3-fpm-buster-console
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.3
        BASEOS: buster

  php74-fpm-buster-console:
    image: my127/spryker:7.4-fpm-buster-console
    build:
      context: ./
      dockerfile: console.Dockerfile
      args:
        VERSION: 7.4
        BASEOS: buster

